### PR TITLE
MNT: Clean up of conf.py and conftest.py

### LINKED ISSUE #102: Clean up `conftest.py` and `docs/conf.py`
Both have some cruft left over from astropy-helpers....

### PR DESCRIPTION
**Pull request by pllim**
Follow-up of #101 

Fix #102

### CODE REVIEW

**Comment by pllim** [comment]
Hmm... Adding `TESTED_VERSIONS` still shows "Astropy 4.0," not "astrowidgets ..."

@astrofrog , is it possible that `TESTED_VERSIONS` does not work with `tox`? It works fine in my other projects that don't use `tox`.

**Comment by pllim** [comment]
I also don't understand why this change would cause timeout for:

```
        - stage: Comprehensive tests
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.14
```

🤷‍♀

**Comment by mwcraig** [comment]
That timeout is strange...tempting to not use conda for this. I'm re-running that test to see what happens.

**Comment by mwcraig** [comment]
Still fails, I'm going to try switch to `pip install` on that job...

**Comment by mwcraig** [comment]
Good news: the travis failure isn't related to your changes!

Bad news: I think it is timing out on the solve and have no idea why!

Some attempts at fixing are incoming...

**Comment by mwcraig** [comment]
If this latest fix doesn't work I'll open a separate PR to play around on, and either way will clean up the commit history here.

**Comment by mwcraig** [comment]
Still failing, so I'm going to open a separate PR to work on that case.

**Comment by mwcraig** [comment]
Close/reopen to trigger tests...

**Comment by mwcraig** [comment]
codecov seems a little confused, but tests are passing so I'm merging.

**Comment by pllim** [comment]
Thanks, @mwcraig !

**Pull request merged**
