### PR TITLE
Add helpers

### PR DESCRIPTION
**Pull request by eteq**
I just tried to build and it failed due to the lack of the helpers.  This commit adds them.  I'm guessing this was just an oversight in #6, @mwcraig ?  If so, feel free to just hit merge here.

### CODE REVIEW

**Comment by pllim** [comment]
Huh pretty sure I saw Matt add some of those in one of the diff notifications... :thinking: 

Oh... Was it pllim/astrowidgets#1 ?

**Comment by pllim** [comment]
Oh, I think Matt added them in #7 but it is not merged yet.

**Comment by eteq** [comment]
Ahh, gotcha. I won't merge now then since it might be a pain for @mwcraig to disentangle it from #7.  But if you think #7 will take a bit, maybe merge this and rebase @mwcraig ? (I'll leave it to you to make the final call.)

**Comment by eteq** [comment]
NOTE: this branch should be deleted when merged/closed - it's only in this repo because it was prior to the migration to `astropy` (and would normally have been in my fork)

**Comment by mwcraig** [comment]
I'm about to merge #7 once travis passes....

**Comment by mwcraig** [comment]
Closed by #7

**Pull request closed without merging**
